2024-07-29 12:27:30,554 - ERROR - Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\manage.py", line 22, in <module>
    main()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\apps\registry.py", line 124, in populate
    app_config.ready()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\contrib\admin\apps.py", line 27, in ready
    self.module.autodiscover()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\contrib\admin\__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\utils\module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\snippets\admin.py", line 2, in <module>
    from .models import Snippets,Category,Products
ImportError: cannot import name 'Snippets' from 'snippets.models' (C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\snippets\models.py)

2024-07-29 12:27:31,489 - ERROR - Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\manage.py", line 22, in <module>
    main()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\apps\registry.py", line 124, in populate
    app_config.ready()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\contrib\admin\apps.py", line 27, in ready
    self.module.autodiscover()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\contrib\admin\__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\utils\module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\snippets\admin.py", line 2, in <module>
    from .models import Snippets,Category,Products
ImportError: cannot import name 'Snippets' from 'snippets.models' (C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\snippets\models.py)

2024-07-29 12:29:01,467 - ERROR - Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\manage.py", line 22, in <module>
    main()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\apps\registry.py", line 124, in populate
    app_config.ready()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\contrib\admin\apps.py", line 27, in ready
    self.module.autodiscover()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\contrib\admin\__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\utils\module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\snippets\admin.py", line 2, in <module>
    from .models import Snippets,Category,Products
ImportError: cannot import name 'Snippets' from 'snippets.models' (C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\snippets\models.py)

2024-07-29 12:29:02,399 - ERROR - Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\manage.py", line 22, in <module>
    main()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\apps\registry.py", line 124, in populate
    app_config.ready()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\contrib\admin\apps.py", line 27, in ready
    self.module.autodiscover()
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\contrib\admin\__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\.venv\Lib\site-packages\django\utils\module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\snippets\admin.py", line 2, in <module>
    from .models import Snippets,Category,Products
ImportError: cannot import name 'Snippets' from 'snippets.models' (C:\Users\user\OneDrive\Desktop\MachineLearning\django\skepta\snippets\models.py)

